---
- name: Create Nginx directiry
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: 0775
  with_items:
    - /opt/nginx/conf/
    - /opt/nginx/secrets/

- name: Copy Nginx config
  copy:
    src: ../nginx/conf/{{domains[current_env]}}
    dest: /opt/nginx/conf/

# copy default Nginx config for environments with certbot
- name: Copy default Nginx config
  copy:
    src: ../nginx/conf/default.conf
    dest: /opt/nginx/conf/
  when: current_env != "vagrant"