version: '3.8'
services:

  db:
    image: postgis/postgis:12-2.5-alpine
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USERNAME
    env_file:
      - .env
    expose:
      - "5432"

  django:
    build: .
    expose:
      - "8000"
    environment:
      - DB_HOST=db
    env_file:
      - .env
    command: ./entrypoint.sh
    depends_on:
      - db

  nginx:
    build: ./nginx/
    volumes:
      - nginx-configs:/etc/nginx/conf.d/
      - httpasswd:/etc/nginx/secrets/
    ports:
      - 80:80
    depends_on:
      - django

volumes:
   nginx-configs:
      driver_opts:
        type: none
        #device: /opt/nginx/conf
        device: /home/alex/Teamvoy/my_projects/links/nginx/conf
        o: bind
   httpasswd:
      driver_opts:
        type: none
        #device: /opt/nginx/secrets
        device: /home/alex/Teamvoy/my_projects/links/nginx/secrets/
        o: bind