version: '3.8'
services: 
  django:
    build: .
    #volumes:
    #  - /home/alex/Teamvoy/my_projects/links/backend/:/backend/
    expose:
      - "8000"
    command: ./entrypoint.sh

  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - nginx-configs:/etc/nginx/conf.d/
    ports:
      - 80:80
    depends_on:
      - django

volumes:
   nginx-configs:
      driver_opts:
        type: none
        #device: /opt/nginx/
        device: /home/alex/Teamvoy/my_projects/links/nginx/
        o: bind