---
- name: Creates backup directory
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - /var/backups/daily

- name: Copy scripts for creating backups
  copy:
    src: ../scripts/{{ item }}
    dest: /var/backups/
    mode: 0755
  with_items:
    - create_backups.sh
    - copy_backups.sh

- name: Creating Cron job for creating backups
  cron:
    user: root
    name: "creating daily backups"
    minute: "0"
    hour: "0"
    job: "/var/backups/create_backups.sh"

- name: Creating Cron job for copying backups into AWS s3 bucket
  cron:
    user: "{{ item.username }}"
    name: "copy backup to s3 bucket"
    minute: "10"
    hour: "0"
    job: "/var/backups/copy_backups.sh links-backups"
  with_items: "{{ awscli_users }}"