- name: server
  hosts: all
  become: True
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
    project_name: "link_shortener"

  roles:
    - install_docker
    - role: geerlingguy.docker
      docker_install_compose: true
    - copy_nginx_configs
    - copy_env_variables_files
    - cron_setup
    - deploy
