- name: server
  hosts: all
  become: True
  gather_facts: no
  vars_files:
    - ansible_vars/main.yaml

  roles:
    - install_docker
    - role: geerlingguy.docker
      docker_install_compose: true
    - aws_cli_setup
    - copy_nginx_configs
    - copy_env_variables_files
    - cron_setup
    - deploy
