# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.env.enable
    config.vm.define "server" do |machine|
      config.vm.provider "virtualbox" do |v|
        v.memory = 4048
        v.cpus = 4
      end
      machine.vm.network "private_network", ip: "10.2.2.25"
      machine.vm.box = "ubuntu/bionic64"
      machine.vm.provision :ansible do |ansible|
        ansible.playbook = "playbook.yaml"
        ansible.verbose = 'vv'
        ansible.extra_vars = {
          github_user: ENV["REGISTRY_USER"],
          github_token: ENV["REGISTRY_TOKEN"],
          aws_access_key: ENV["AWS_ACCESS_KEY"],
          aws_secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
          server_user: 'vagrant'
        }
      end
    end
  end