version: '3.8'
services:
  nginx:
    ports:
      - 443:443
    labels:
      nginx.proxy: "Certbot"
    volumes:
      - common-ssl:/etc/ssl/certs
      - letsencrypt:/etc/letsencrypt/
    networks:
      - shortener_network

  certbot:
    image: ghcr.io/oleksandrtimoshenko/dns-route53-certbot
    command: /entrypoint.sh
    env_file:
      - .env.certbot
    volumes:
      - common-ssl:/etc/ssl/certs
      - letsencrypt:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
          condition: on-failure
    networks:
      - shortener_network

volumes:
   common-ssl:
   letsencrypt: