---
- name: Log into DockerHub
  community.docker.docker_login:
    username: "{{ github_user }}"
    password: "{{ github_token }}"
    url: ghcr.io

- name: Init a new swarm with default parameters
  docker_swarm:
    state: present
    # only for local testing with Vagrant
    advertise_addr: "10.2.2.25"

- name: Copy compose files
  copy:
    src: "../compose_files/{{ item }}"
    dest: "/opt/{{ item }}"
  loop:
    - docker-compose.yaml
    - docker-compose.certbot.orerride.yaml

- name: Copy filebeat config
  copy:
    src: "../filebeat/{{ item }}"
    dest: "/opt/{{ item }}"
  loop:
    - filebeat_config_docker.yml

- name: Deploy stack from a compose file
  docker_stack:
    state: present
    prune: yes
    name: "{{ project_name }}-stack"
    with_registry_auth: yes
    compose:
      - /opt/docker-compose.yaml
  when: current_env == 'vagrant'

- name: Deploy stack from a compose file
  docker_stack:
    state: present
    prune: yes
    name: "{{ project_name }}-stack"
    with_registry_auth: yes
    compose:
      - /opt/docker-compose.yaml
      - /opt/docker-compose.certbot.orerride.yaml
  when: current_env != 'vagrant'