---
- name: Log into DockerHub
  community.docker.docker_login:
    username: "{{ github_user }}"
    password: "{{ github_token }}"
    url: ghcr.io

- name: Init a new swarm with default parameters
  docker_swarm:
    state: present
    # only for local testing with Vagrant
    advertise_addr: "10.2.2.25"

- name: Copy files with owner and permissions
  copy:
    src: "../{{ item }}"
    dest: "/opt/{{ item }}"
  loop:
    - docker-compose.yaml

- name: Deploy stack from a compose file
  docker_stack:
    state: present
    prune: yes
    name: "{{ project_name }}-stack"
    with_registry_auth: yes
    compose:
      - /opt/docker-compose.yaml