---
- name: add environment file
  template:
    src: ../{{ item }}
    dest: /opt/
  with_items:
    - .env
    - .env.certbot

- name: Copy Nginx authentification credentials
  copy:
    src: ../nginx/secrets/{{ item }}
    dest: /opt/nginx/secrets/{{ item }}
  with_items:
    - .htpasswd