name: Build and puch images

on:   
  push:

env:
  BACKEND_IMAGE_NAME: shortener_backend
  NGINX_IMAGE_NAME: shortener_nginx
  CERTBOT_IMAGE_NAME: dns-route53-certbot
  FILEBEAT_IMAGE_NAME: filebeat-gjango

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Build backend image
        run: docker build . --file ./deploy/Dockerfile --tag $BACKEND_IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Build nginx image
        run: docker build . --file ./nginx/Dockerfile --tag $NGINX_IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"


      - name: Build filebeat image
        run: docker build ./filebeat --tag $FILEBEAT_IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Build certbot image
        run: docker build ./certbot --tag $CERTBOT_IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.WORKFLOW_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push backend image
        run: |
          ./scripts/push_images.sh ${{ github.repository_owner }} $BACKEND_IMAGE_NAME

      - name: Push nginx image
        run: |
          ./scripts/push_images.sh ${{ github.repository_owner }} $NGINX_IMAGE_NAME

      - name: Push certbot image
        run: |
          ./scripts/push_images.sh ${{ github.repository_owner }} $CERTBOT_IMAGE_NAME

      - name: Push filebeat image
        run: |
          ./scripts/push_images.sh ${{ github.repository_owner }} $FILEBEAT_IMAGE_NAME

  security_scanning:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Install trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy

      - name: Log in to registry
        run: echo "${{ secrets.WORKFLOW_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # outdated python packeges
      #- name: Run backend image security scanning
      #  run: |
      #    ./scripts/security_scanning.sh ${{ github.repository_owner }} $BACKEND_IMAGE_NAME

      - name: Run Nginx image security scanning
        run: |
          ./scripts/security_scanning.sh ${{ github.repository_owner }} $NGINX_IMAGE_NAME

      - name: Run Certbot image security scanning
        run: |
          ./scripts/security_scanning.sh ${{ github.repository_owner }} $CERTBOT_IMAGE_NAME
